CREATE DATABASE ITStep;
GO

USE ITStep;
GO

CREATE TABLE LessonDay(
	ID INT PRIMARY KEY IDENTITY(1,1),
	[Name] VARCHAR(50)
);
GO

CREATE TABLE LessonHour(
	ID INT PRIMARY KEY IDENTITY(1,1),
	[Start] TIME NOT NULL,
	[Stop] TIME NOT NULL
);
GO

CREATE TABLE LessonHourInDay(
	ID INT PRIMARY KEY IDENTITY(1,1),
	LessonDayFK INT NOT NULL,
	LessonHourFK INT NOT NULL,
	FOREIGN KEY (LessonDayFK) REFERENCES LessonDay(ID),
	FOREIGN KEY (LessonHourFK) REFERENCES LessonHour(ID)
)

CREATE TABLE Teacher(
	ID INT PRIMARY KEY IDENTITY(1,1),
	[Name] VARCHAR(50) NOT NULL,
	Salary MONEY NOT NULL
);
GO

CREATE TABLE Theme(
	ID INT PRIMARY KEY IDENTITY(1,1),
	[Subject] VARCHAR(50)

);
GO

CREATE TABLE TeacherReadTheme(  -- спросить нужен ли тут ключь)
	ID INT PRIMARY KEY IDENTITY(1,1),
	TeacherFK INT NOT NULL,
	ThemeFK INT NOT NULL,
	FOREIGN KEY (TeacherFK) REFERENCES Teacher(ID),
	FOREIGN KEY (ThemeFK) REFERENCES Theme(ID)
)

CREATE TABLE Faculty(
	ID INT PRIMARY KEY IDENTITY(1,1),
	[Name] VARCHAR(50),
	HeadFaculty VARCHAR(50)
);
GO

CREATE TABLE Student(
	ID INT PRIMARY KEY IDENTITY(2020001, 1),
	[Name] VARCHAR(50),
	Debt BIT,
	DateStart DATE NOT NULL
);
GO

CREATE TABLE Grupe(
	ID INT PRIMARY KEY IDENTITY(10001, 1),
	[Name] VARCHAR(50)
);
GO

CREATE TABLE StudentsInGrope(
	GrupeFK INT NOT NULL,
	StudentFK INT NOT NULL,
	PRIMARY KEY(GrupeFK, StudentFK),
	FOREIGN KEY(GrupeFK) REFERENCES Grupe(ID),
	FOREIGN KEY(StudentFK) REFERENCES Student(ID)
);
GO

CREATE TABLE GrupesInFaculty(
	FacultyFK INT NOT NULL,
	GrupeFK INT NOT NULL,
	PRIMARY KEY(FacultyFK, GrupeFK),
	FOREIGN KEY(FacultyFK) REFERENCES Faculty(ID),
	FOREIGN KEY(GrupeFK) REFERENCES Grupe(ID)
);
GO

CREATE TABLE DaysStadyGrupe(
	GrupeFK INT NOT NULL,
	DayFK INT NOT NULL,
	LessonHourInDayFK INT NOT NULL,
	PRIMARY KEY(GrupeFK, DayFK),
	FOREIGN KEY(GrupeFK) REFERENCES Grupe(ID),
	FOREIGN KEY(DayFK) REFERENCES LessonDay(ID),
	FOREIGN KEY(LessonHourInDayFK) REFERENCES LessonHourInDay(ID)
);
GO

CREATE TABLE Timetable(
	ID INT PRIMARY KEY IDENTITY(2020001,1),
	GrupeFK INT NOT NULL, 
	ThemeFK INT NOT NULL,
	TeacherFK INT NOT NULL,
	DayFK INT NOT NULL,
	HourFK INT NOT NULL,
	FOREIGN KEY(GrupeFK) REFERENCES Grupe(ID),
	FOREIGN KEY(ThemeFK) REFERENCES Theme(ID),
	FOREIGN KEY(TeacherFK) REFERENCES Teacher(ID),
	FOREIGN KEY(DayFK) REFERENCES LessonDay(ID),
	FOREIGN KEY(HourFK) REFERENCES LessonHour(ID)
);
GO